import { appendFileSync, closeSync, constants, fchmodSync, lstatSync, mkdirSync, openSync, readFileSync, readdirSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { isPrivatePathSync, protectPrivatePathSync } from './private-files.ts';

export function claudeUsageDirectory(env: NodeJS.ProcessEnv = process.env) {
  return env.SMART_CODEX_STATE_DIR ? join(env.SMART_CODEX_STATE_DIR, 'claude-logs') : fileURLToPath(new URL('../.smart-claude/', import.meta.url));
}
type Counts = { input_tokens: number; output_tokens: number; cache_read_input_tokens: number; cache_creation_input_tokens: number };
export function createClaudeUsage(directory?: string) {
  const tokens: Counts = { input_tokens: 0, output_tokens: 0, cache_read_input_tokens: 0, cache_creation_input_tokens: 0 };
  let routes = 0, completed = 0, aborted = 0, unknownUsage = 0, classifications = 0, jevInput = 0, jevOutput = 0, ended = false;
  let lastRoute: Record<string, unknown> | null = null, lastActualModel: string | null = null;
  let path: string | undefined, fd: number | undefined;
  if (directory) try {
    const created = mkdirSync(directory, { recursive: true, mode: 0o700 });
    if (created) protectPrivatePathSync(directory, true);
    if (!isPrivatePathSync(directory, true)) throw new Error('Private log directory required');
    path = join(directory, `${Date.now()}-${randomUUID()}.jsonl`);
    fd = openSync(path, constants.O_CREAT | constants.O_EXCL | constants.O_WRONLY | constants.O_APPEND | constants.O_NOFOLLOW, 0o600);
    fchmodSync(fd, 0o600); if (process.platform === 'win32') protectPrivatePathSync(path);
  } catch { if (fd !== undefined) closeSync(fd); fd = undefined; path = undefined; }
  const snapshot = () => ({ format: 'modelrudder-claude-1', ended, routes, completed, aborted, unknownUsage,
    classifications, jevInput, jevOutput, tokens: { ...tokens }, lastActualModel, lastRoute });
  const publish = () => {
    if (fd === undefined) return;
    try { appendFileSync(fd, `${JSON.stringify({ ...snapshot(), timestamp: new Date().toISOString() })}\n`); }
    catch { closeSync(fd); fd = undefined; }
  };
  return {
    get path() { return path; }, snapshot,
    route(meta: Record<string, unknown>) {
      routes++;
      // Metadata is generated by the router, never a raw plugin/provider blob.
      lastRoute = Object.fromEntries(['model', 'reason', 'proposed', 'reportedConfidence', 'mode', 'policyVersion', 'policyHash', 'classifierVersion', 'routingLatencyMs'].map(key => [key, meta[key]]));
      if (meta.classifierVersion) classifications++;
      const usage = meta.classifierUsage as { inputTokens?: number; outputTokens?: number } | undefined;
      if (Number.isSafeInteger(usage?.inputTokens)) jevInput += usage!.inputTokens!;
      if (Number.isSafeInteger(usage?.outputTokens)) jevOutput += usage!.outputTokens!;
      publish();
    },
    complete(meta: Record<string, unknown>) {
      completed++; if (meta.isAborted) aborted++;
      const usage = meta.usage as (Counts & { model: string }) | undefined;
      if (!usage) unknownUsage++;
      else { for (const key of Object.keys(tokens) as (keyof Counts)[]) tokens[key] += usage[key]; lastActualModel = usage.model; }
      publish();
    },
    close() { ended = true; publish(); if (fd !== undefined) { closeSync(fd); fd = undefined; } },
  };
}

export function formatClaudeUsage(s: ReturnType<ReturnType<typeof createClaudeUsage>['snapshot']>) {
  return `Claude routing: ${s.routes} decisions, ${s.classifications} classifications; ${s.completed} completed turns (${s.aborted} interrupted).\n` +
    `Reported tokens: ${s.tokens.input_tokens} input + ${s.tokens.cache_read_input_tokens} cache read + ${s.tokens.cache_creation_input_tokens} cache write; ${s.tokens.output_tokens} output.\n` +
    `Jev reported tokens: ${s.jevInput} input, ${s.jevOutput} output. Usage may be partial (${s.unknownUsage} turns without counts, ${Math.max(0, s.routes - s.completed)} without completion reports); no quota/savings estimate.\n`;
}
export function runClaudeReport(args: string[], directory = claudeUsageDirectory(), out = (text: string) => process.stdout.write(text)) {
  if (args.length) throw new Error('Claude report accepts no options.');
  try {
    if (!isPrivatePathSync(directory, true)) throw new Error();
    const name = readdirSync(directory).filter(name => /^\d+-[a-f0-9-]+\.jsonl$/.test(name)).sort().at(-1);
    if (!name) throw new Error();
    const path = join(directory, name);
    if (!isPrivatePathSync(path) || lstatSync(path).size > 16 * 1024 * 1024) throw new Error();
    const lines = readFileSync(path, 'utf8').split('\n'); lines.pop();
    const s = JSON.parse(lines.at(-1) ?? 'null');
    if (s?.format !== 'modelrudder-claude-1' || !s.tokens ||
      !['routes', 'classifications', 'completed', 'aborted', 'unknownUsage', 'jevInput', 'jevOutput'].every(key => Number.isSafeInteger(s[key]) && s[key] >= 0) ||
      !['input_tokens', 'output_tokens', 'cache_read_input_tokens', 'cache_creation_input_tokens'].every(key => Number.isSafeInteger(s.tokens[key]) && s.tokens[key] >= 0)) throw new Error();
    out(formatClaudeUsage(s)); return 0;
  } catch { out('No readable private Claude usage report yet. Start smart-claude first.\n'); return 1; }
}
